// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  [x: string]: string | undefined;
  hours__list: string | undefined;
  day: string | undefined;
  day__date: string | undefined;
  day__image: string | undefined;
  day__temp: string | undefined;
}
export const cssExports: CssExports;
export default cssExports;
