// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  day__current: string | undefined;
  day: string | undefined;
  day_active: string | undefined;
  day__date: string | undefined;
  day__image: string | undefined;
  day__temp: string | undefined;
  days: string | undefined;
  days__list: string | undefined;
  hour: string | undefined;
  hour__time: string | undefined;
  hour__image: string | undefined;
  hour__temp: string | undefined;
  hours: string | undefined;
  hours__container: string | undefined;
  hours__list: string | undefined;
}
export const cssExports: CssExports;
export default cssExports;
