// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  days: string | undefined;
  days__list: string | undefined;

}
export const cssExports: CssExports;
export default cssExports;
