// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  time: string | undefined;
  time__city: string | undefined;
  time__your: string | undefined;
  time__clock: string | undefined;
  time__date: string | undefined;

}
export const cssExports: CssExports;
export default cssExports;
