// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  input: string | undefined;
  input__input: any;
  input__input_error: any;

}
export const cssExports: CssExports;
export default cssExports;
