// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  input: string | undefined;
  input__input: string | undefined;
  input__input_error: string | undefined;

}
export const cssExports: CssExports;
export default cssExports;
